/*use master
go
IF EXISTS (SELECT * FROM SYS.databases WHERE NAME = 'THUOC')
drop database THUOC
go
create database THUOC
go*/
use THUOC
go


CREATE TABLE [dbo].[tblNhomthuoc]
(
	[MANHOM] NVARCHAR(10) NOT NULL PRIMARY KEY, 
    [TENNHOM] NVARCHAR(50) NOT NULL, 
    [GHICHU] NCHAR(10) NULL
)

CREATE TABLE [dbo].[tblThuoc]
(	
	[MATHUOC] NVARCHAR(20) NOT NULL PRIMARY KEY, 
	[MANHOM] NVARCHAR(10) not null FOREIGN KEY ([MANHOM]) REFERENCES [dbo].[tblNhomthuoc] ([MANHOM]),
    [TENTHUOC] NVARCHAR(100) NOT NULL, 
    [HOATCHATCHINH] NVARCHAR(100) NOT NULL, 
    [HAMLUONG] NVARCHAR(80) NULL, 
	[HANGSX] NVARCHAR(50) NOT NULL,
	[NUOCSX] NVARCHAR(50) NULL,
    [QUYCACHDONGGOI] NVARCHAR(80) NOT NULL,
	[DVT] NVARCHAR(50) NOT NULL, 
    
)

CREATE TABLE [dbo].[tblNhanvien]
(
	[MANHANVIEN] NVARCHAR(20) NOT NULL PRIMARY KEY, 
    [TENNHANVIEN] NVARCHAR(50) NOT NULL, 
    [DIACHI] NVARCHAR(100) NOT NULL,
    [SDT] NVARCHAR(50) NOT NULL,
	[TAIKHOAN] nvarchar(20) not null,
	[MATKHAU] nvarchar(20) NOT NULL,
	[QUYEN] nvarchar(10) NOT NULL,
)

CREATE TABLE [dbo].[tblKhachhang]
(
	[MAKHACH] NVARCHAR(20) NOT NULL PRIMARY KEY, 
    [TENKHACH] NVARCHAR(50) NOT NULL, 
    [DIACHI] NVARCHAR(100) NOT NULL,
	[EMAIL] NVARCHAR(50) NOT NULL,
    [SDT] NVARCHAR(50)  NULL
)

CREATE TABLE [dbo].[tblNhacungcap]
(
	[MANCC] NVARCHAR(20) NOT NULL PRIMARY KEY, 
    [TENNCC] NVARCHAR(100) NOT NULL, 
    [SDT] NVARCHAR(20) NOT NULL, 
    [EMAIL] NVARCHAR(50) NOT NULL, 
    [MST]  NVARCHAR(50)  NULL
)

CREATE TABLE [dbo].[tblPhieunhap]
(
	[MANHAP] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [NGAYNHAP] DATE NOT NULL, 
    [MANCC] NVARCHAR(20) FOREIGN KEY ([MANCC]) REFERENCES [dbo].[tblNhacungcap] ([MANCC]),
    [TONGTIEN] INT NOT NULL, 
    [GHICHU] NVARCHAR(50) NULL
)

CREATE TABLE [dbo].[tblCTPhieunhap]
(
	[MANHAP] NVARCHAR(50) FOREIGN KEY ([MANHAP]) REFERENCES [dbo].[tblPhieunhap] ([MANHAP]),
	[MATHUOC] NVARCHAR(20) FOREIGN KEY ([MATHUOC]) REFERENCES [dbo].[tblThuoc] ([MATHUOC]),
    [LOSX] int NOT NULL, 
	[HSD] date not null,
    [DVT] NVARCHAR(50) NOT NULL, 
    [DONGIA] float NOT NULL, 
    [SLUONG] int not NULL,
	[THANHTIEN] float not null,
	CONSTRAINT [PK_CT_Phieunhap] PRIMARY KEY CLUSTERED ([MANHAP] ASC, [MATHUOC] ASC),
)

CREATE TABLE [dbo].[tblHoadonban]
(
	[MABAN] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [NGAYNHAP] DATE NOT NULL, 
    [MAKHACH] NVARCHAR(20) FOREIGN KEY ([MAKHACH]) REFERENCES [dbo].[tblKhachhang] ([MAKHACH]),
	[MANHANVIEN] NVARCHAR(20) FOREIGN KEY ([MANHANVIEN]) REFERENCES [dbo].[tblNhanvien] ([MANHANVIEN]),
    [TONGTIEN] INT NOT NULL, 
    [GHICHU] NVARCHAR(50) NULL
)

CREATE TABLE [dbo].[tblCTHoadonban]
(
	[MABAN] NVARCHAR(50) FOREIGN KEY ([MABAN]) REFERENCES [dbo].[tblHoadonban] ([MABAN]),
	[MATHUOC] NVARCHAR(20) FOREIGN KEY ([MATHUOC]) REFERENCES [dbo].[tblThuoc] ([MATHUOC]),
    [LOSX] int NOT NULL, 
    [DVT] NVARCHAR(50) NOT NULL, 
    [DONGIA] float NOT NULL, 
    [SLUONG] int not NULL,
	[THANHTIEN] float not null,
	CONSTRAINT [PK_CT_Hoadonban] PRIMARY KEY CLUSTERED ([MABAN] ASC, [MATHUOC] ASC),
)

